namespace :import do
  desc "
    Import a JSON file which has been generated by mongoexport
  "
  task json: :environment do |_t, args|
    JsonImporter.new(model_class: args.extras[0], file: args.extras[1]).call
  end
end
