namespace :import do
  desc "Import a JSON file which has been generated by mongoexport"
  task json: :environment do |_t, args|
    model_class = args.extras[0]
    log_file = nil
    log_file_path = "tmp/#{model_class}_migration_logs.txt"
    if log_file_path
      log_file = File.open(log_file_path, "w")
    end

    JsonImporter.new(model_class:, import_file: args.extras[1], log_file:).call
  rescue StandardError => e
    warn e.full_message
  ensure
    log_file&.close
  end
end
