api_version: 2
defaults:
  auto_merge: true
  update_external_dependencies: false # TODO: enable after verifying that this repo meets the conditions
overrides:
  - dependency: rails # should be upgraded manually, see https://docs.publishing.service.gov.uk/manual/keeping-software-current.html#rails
    auto_merge: false
