module Ga4TestHelpers
  def disable_form_submit
    # Disable submission of the form so that all event data can be gathered
    # including the data collected on the "Save" (or equivalent) button being clicked
    execute_script("document.querySelector('form').addEventListener('submit',function(e){e.preventDefault()})")
  end

  def get_event_data
    # Gets the data generated by user events up to and including submitting the form
    data_layer_items = evaluate_script("window.dataLayer")
    event_data = []

    data_layer_items.each do |item|
      if item["event_data"]
        event_data << item["event_data"]
      end
    end

    event_data
  end

  def get_search_data
    data_layer_items = evaluate_script("window.dataLayer")
    # data_layer_items = evaluate_script("setTimeout(function(){window.dataLayer},1000)")

    search_data = []

    data_layer_items.each do |item|
      # if item["search_data"]
      if item["event"]
        # search_data << item["search_data"]
        search_data << item
      end
    end

    search_data
    # data_layer_items
    # evaluate_script("setTimeout(function(){window.dataLayer},1000)")
  end
end
