module Ga4TestHelpers
  def disable_form_submit
    # Disable submission of the form so that all event data can be gathered
    # including the data collected on the "Save" (or equivalent) button being clicked
    execute_script("document.querySelector('form').addEventListener('submit',function(e){e.preventDefault()})")
  end

  def get_event_data
    # Gets the data generated by user events up to and including submitting the form
    data_layer_events = evaluate_script("window.dataLayer")
    event_data = []

    data_layer_events.each do |event|
      if event["event_data"]
        event_data << event["event_data"]
      end
    end

    event_data
  end
end
