module Ga4TestHelpers
  def disable_form_submit
    execute_script("document.querySelector('form').addEventListener('submit',function(e){e.preventDefault()})")
  end

  def disable_links
    execute_script("document.addEventListener('click',function(e){if(e.target.href)(e.preventDefault())})")
  end

  def get_event_data
    # Gets the data generated by user events up to and including submitting the form
    data_layer_items = evaluate_script("window.dataLayer")
    event_data = []

    data_layer_items.each do |item|
      if item["event_data"]
        event_data << item["event_data"]
      end
    end

    event_data
  end

  def get_search_data
    data_layer_items = evaluate_script("window.dataLayer")
    search_data = []

    data_layer_items.each do |item|
      if item["event"] && item["event"]["search_results"]
        search_data = item["search_results"]
      end
    end

    search_data
  end
end
